apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ope-log-collector
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
