apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ope-webhook-role
rules:
- apiGroups: ["user.openshift.io"]
  resources: ["pods", "groups"]
  verbs: ["get", "list", "watch", "patch"]
