apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
# EDIT VALUE HERE BEFORE APPLYING
namespace: <namespace>
