name: Run tests for assign-class-label

on:
  push:
    paths:
    - container-images/assign-class-label/**
  pull_request:
    paths:
    - container-images/assign-class-label/**
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        working-directory: ./container-images/assign-class-label
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run tests
        working-directory: ./container-images/assign-class-label
        run: |
          pytest -v
